config/routes.rb
BottomlessSoupBowl::Application.routes.draw do

  get "users/index"
  get "users/show"

  devise_for :users

  resources :flavors
  resources :bsb_feeds

  match 'bsb_feeds/:id/refresh' => 'bsb_feeds#refresh', :as => :refresh_bsb_feed
  match 'bsb_feeds/:id/next' => 'bsb_feeds#next', :as => :next_feed_story
  match 'bsb_feeds/:id/prev' => 'bsb_feeds#prev', :as => :prev_feed_story
  match 'bsb_feeds/:id/start' => 'bsb_feeds#start', :as => :start_feed_story

  match 'all_bsb_feeds' => 'bsb_feeds#all', :as => :all_bsb_feeds

  match 'all_bsb_feeds/refresh' => 'bsb_feeds#refresh_all', :as => :refresh_all
  match 'all_bsb_feeds/next' => 'bsb_feeds#next_all', :as => :next_all_story
  match 'all_bsb_feeds/prev' => 'bsb_feeds#prev_all', :as => :prev_all_story
  match 'all_bsb_feeds/start' => 'bsb_feeds#start_all', :as => :start_all_story

  match 'users/showfeeds/:id' => 'users#show', :as => :user

  match 'flavors/:id/refresh' => 'flavors#calculate_scores', :as => :calculate_flavor_scores
  match 'flavors/:id/next' => 'flavors#next', :as => :next_flavor_story
  match 'flavors/:id/prev' => 'flavors#prev', :as => :prev_flavor_story
  match 'flavors/:id/start' => 'flavors#start', :as => :start_flavor_story

  match 'flavors/:id/set_algorithm' => 'flavors#set_algorithm', :as => :set_flavor_algorithm

  match 'users' => 'users#index'
  match 'users/fetch' => 'users#fetch', :as => :fetch_user_stories

  match 'users/:id/feeds' => 'users#feeds', :as => :user_feeds

  match 'import_feeds' => 'users#import_feeds', :as => :import_feeds

  match 'do_feed_import' => 'users#do_feed_import', :as => :do_feed_import

  match 'remove_all_feeds' => 'users#remove_all_feeds', :as => :remove_all_feeds

  root :to => 'users', :action => 'show_current'

end

app/models/flavor.rb
class Flavor < ActiveRecord::Base
  attr_accessible :name, :read_index, :sort_progress
  belongs_to :user
  has_one :sorter
  has_many :bsb_feeds
  has_many :stories, through: :user

  def score_stories
    # bsb_feeds.each do |bfeed|
    #   bfeed.stories.each do |story|
    #     story.score = sorter.score_individual(story)
    #     story.save
    #   end
    # end
    self.sort_progress = 0.0
    sorted = 0
    self.save
    stories.each do |story|
      story.score = sorter.score_individual(story)
      story.save
      sorted += 1
      self.sort_progress = (sorted.to_f / stories.size) * 100
      puts sort_progress
      self.save
    end

  end

  def get_story(rindex)
    # titles = bsb_feeds.pluck(:title)
    allstories = stories.where(:bsb_feed_id => bsb_feeds.pluck(:id)).order("score DESC")[rindex]
    # allstories = []
    # stories.each do |story|
    #   if titles.include?(story.bsb_feed.title)
    #     allstories << story
    #   end
    # end


    # bsb_feeds.each do |bfeed|
    #   bfeed.stories.each do |story|
    #     if(story && story.score && usr.user_stats.stories.include?(story))
    #       allstories << story
    #     end
    #   end
    # end

    #allstories[rindex]
    #do not want to be sorting on every page view
    #allstories.sort_by(&:score).reverse[rindex]
  end

  def get_unread_count
    stories.where(:bsb_feed_id => bsb_feeds.pluck(:id)).count
  end

end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
  @available_algorithms = [["Facebook","Fbook"],["Recentness","Time"]]
  before_filter :authenticate_user!

  # GET /flavors
  # GET /flavors.json
  def index
    @flavors = current_user.flavors.all
    @algorithms = [["Facebook","fbook"],["Timeliness","time"],["Mix","fbook_plus_time"]] #would like to not have to hardcode this

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flavors }
    end
  end

  # GET /flavors/1
  # GET /flavors/1.json
  def show
    @flavor = Flavor.find(params[:id])

    @story = @flavor.get_story(@flavor.read_index)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flavor }
    end
  end

  # GET /flavors/new
  # GET /flavors/new.json
  def new
    @flavor = Flavor.new
    @user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @flavor }
    end
  end

  # GET /flavors/1/edit
  def edit
    @flavor = Flavor.find(params[:id])
    @user = current_user
  end

  # POST /flavors
  # POST /flavors.json
  def create
    @flavor = Flavor.new(params[:flavor])
    @user = current_user
    incl_feeds = params["Feeds"]
    #puts params["Feeds"]
    incl_feeds.each do |t|
      fobj = BsbFeed.where("title = ?",t)
      if(fobj)
        @flavor.bsb_feeds << fobj
      end
    end
    @flavor.read_index = 0
    @flavor.user = current_user
    @flavor.sorter = Sorter.create(name: "Default", algorithm: "time")
    # if(@flavor.valid?)
    #   current_user.bsb_feeds.each do |bfeed|
    #     @flavor.bsb_feeds << bfeed
    #   end
    # end

    respond_to do |format|
      if @flavor.save
        format.html { redirect_to calculate_flavor_scores_path(@flavor) }
        format.json { render json: @flavor, status: :created, location: @flavor }
      else
        format.html { render action: "new" }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /flavors/1
  # PUT /flavors/1.json
  def update
    @flavor = Flavor.find(params[:id])

    respond_to do |format|
      if @flavor.update_attributes(params[:flavor])
        format.html { redirect_to @flavor, notice: 'Flavor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flavors/1
  # DELETE /flavors/1.json
  def destroy
    @flavor = Flavor.find(params[:id])
    @flavor.destroy

    respond_to do |format|
      format.html { redirect_to flavors_url }
      format.json { head :no_content }
    end
  end

  def calculate_scores
    @flavor = Flavor.find(params[:id])
    @flavor.delay.score_stories
    @flavor.read_index = 0
    @flavor.save

    respond_to do |format|
      format.html { redirect_to flavors_url }
      format.json { head :no_content }
    end
  end

  def next
    @flavor = Flavor.find(params[:id])
    if params[:keep_unread]
      @flavor.read_index+=1
    else
      current_user.mark_read(@flavor.get_story(@flavor.read_index))
    end
    @flavor.save

    respond_to do |format|
      format.html { redirect_to @flavor  }
      format.json { head :no_content }
    end
  end

  def prev
    @flavor = Flavor.find(params[:id])
    if params[:keep_unread]
      @flavor.read_index-=1
    else
      current_user.mark_read(@flavor.get_story(@flavor.read_index))
    end
    @flavor.save

    respond_to do |format|
      format.html { redirect_to @flavor  }
      format.json { head :no_content }
    end
  end

  def start
    @flavor = Flavor.find(params[:id])
    @flavor.read_index = 0
    @flavor.save

    respond_to do |format|
      format.html { redirect_to @flavor  }
      format.json { head :no_content }
    end
  end

  def set_algorithm
    @flavor = Flavor.find(params[:id])
    if params[:algorithm]
      @flavor.sorter.algorithm = params[:algorithm]
      @flavor.sorter.save
    end

    respond_to do |format|
      format.html { redirect_to flavors_path  }
      format.json { head :no_content }
    end
  end
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/views/flavors/_form.html.erb
<%= form_for(@flavor) do |f| %>
  <% if @flavor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flavor.errors.count, "error") %> prohibited this flavor from being saved:</h2>

      <ul>
      <% @flavor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% @user.bsb_feeds.each do |feed| %>
  <li>
    <%= check_box_tag("Feeds[]",feed.title) %>
    <%= " #{feed.title}" %>
  </li>
  <% end %>

<% end %>

app/views/flavors/edit.html.erb
<h1>Editing flavor</h1>

<%= render 'form' %>

<%= link_to 'Show', @flavor %> |
<%= link_to 'Back', flavors_path %>

app/views/flavors/index.html.erb
<h1>Listing flavors</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @flavors.each do |flavor| %>
  <tr>
    <td><%= link_to flavor.name, flavor %></td>
    <td><%= "(#{flavor.get_unread_count})" %></td>
    <td><%= link_to 'Sort', calculate_flavor_scores_path(flavor) %></td>
    <td><%= link_to 'Edit', edit_flavor_path(flavor) %></td>
    <td><%= link_to 'Destroy', flavor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= form_tag set_flavor_algorithm_path(flavor) do %>

        <%= select_tag 'algorithm',

          options_for_select(@algorithms, flavor.sorter.algorithm),

          onchange: 'this.form.submit()' %>
        <%= submit_tag 'set' %>
        <%= javascript_tag "$('.locale input').hide()" %>
        <% end %>
        </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Flavor', new_flavor_path %>
<%= link_to 'Back', current_user, data: { keybinding: 'b' }  %>

app/views/flavors/new.html.erb
<h1>New flavor</h1>

<%= render 'form' %>

<%= link_to 'Back', flavors_path %>

app/views/flavors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= @flavor.name %> Soup</b>
</p>

<%= link_to 'Prev', prev_flavor_story_path(@flavor), data: { keybinding: 'K' } %>
<%= link_to '', prev_flavor_story_path(@flavor, :keep_unread => 1), data: { keybinding: 'k' }  %>
<%= link_to 'Next', next_flavor_story_path(@flavor), data: { keybinding: 'J' } %>
<%= link_to '', next_flavor_story_path(@flavor, :keep_unread => 1), :data => { keybinding: 'j' } %>

<% if @story %>
<%= render @story %>
<% else %>
<h2> Failed to fetch story! </h2>
<% end %>


<%= link_to 'Start', start_flavor_story_path(@flavor), data: { keybinding: 'q' } %>
<%= link_to 'Prev (k)', prev_flavor_story_path(@flavor) %>
<%= link_to 'Next (j)', next_flavor_story_path(@flavor) %>
<p></p>

<p>
  <b>Read index:</b>
  <%= @flavor.read_index %>
</p>


<%= link_to 'Edit', edit_flavor_path(@flavor) %> |
<%= link_to 'Back', flavors_path, data: { keybinding: 'b' } %>