config/routes.rb
BottomlessSoupBowl::Application.routes.draw do

  get "users/index"
  get "users/show"

  devise_for :users

  resources :flavors
  resources :bsb_feeds

  match 'bsb_feeds/:id/refresh' => 'bsb_feeds#refresh', :as => :refresh_bsb_feed
  match 'bsb_feeds/:id/next' => 'bsb_feeds#next', :as => :next_feed_story
  match 'bsb_feeds/:id/prev' => 'bsb_feeds#prev', :as => :prev_feed_story
  match 'bsb_feeds/:id/start' => 'bsb_feeds#start', :as => :start_feed_story

  match 'all_bsb_feeds' => 'bsb_feeds#all', :as => :all_bsb_feeds

  match 'all_bsb_feeds/refresh' => 'bsb_feeds#refresh_all', :as => :refresh_all
  match 'all_bsb_feeds/next' => 'bsb_feeds#next_all', :as => :next_all_story
  match 'all_bsb_feeds/prev' => 'bsb_feeds#prev_all', :as => :prev_all_story
  match 'all_bsb_feeds/start' => 'bsb_feeds#start_all', :as => :start_all_story

  match 'users/showfeeds/:id' => 'users#show', :as => :user

  match 'flavors/:id/refresh' => 'flavors#calculate_scores', :as => :calculate_flavor_scores
  match 'flavors/:id/next' => 'flavors#next', :as => :next_flavor_story
  match 'flavors/:id/prev' => 'flavors#prev', :as => :prev_flavor_story
  match 'flavors/:id/start' => 'flavors#start', :as => :start_flavor_story

  match 'flavors/:id/set_algorithm' => 'flavors#set_algorithm', :as => :set_flavor_algorithm

  match 'users' => 'users#index'
  match 'users/fetch' => 'users#fetch', :as => :fetch_user_stories

  match 'users/:id/feeds' => 'users#feeds', :as => :user_feeds

  match 'import_feeds' => 'users#import_feeds', :as => :import_feeds

  match 'do_feed_import' => 'users#do_feed_import', :as => :do_feed_import

  match 'remove_all_feeds' => 'users#remove_all_feeds', :as => :remove_all_feeds

  root :to => 'users', :action => 'show_current'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :last_refresh
  # attr_accessible :title, :body
  has_one :user_stats
  has_many :stories, :through => :user_stats
  has_and_belongs_to_many :bsb_feeds
  has_many :flavors

  def addFeed (feed)
    if feed
      bsb_feeds.build(last_update: feed.last_update, read_index: feed.read_index, title: feed.title, url: feed.url)
    end
  end

  def remove_all_feeds
    bsb_feeds.each do |bf|
      bf.destroy
    end
  end

  def refresh_stats
    if !self.last_refresh
      self.last_refresh = Time.now - 7.days
    end
    bsb_feeds.each do |feed|
      feed.update_feed
      feed.stories.each do |story|
        if(story.published && (story.published > last_refresh))
          user_stats.stories << story
        end
      end
      #user_stats.stories.save
    end
    self.last_refresh = Time.now
    self.save
  end

  def mark_read(story)
    user_stats.stories.delete(story)
  end

  def import_feeds(file)

    urls = []

    doc = Nokogiri::XML(file)
    doc.xpath("//outline").each do |ent|
      if ent.attribute("xmlUrl")
        urls.push(ent.attribute("xmlUrl").value)
      end
    end
    #urls = import_feeds_from_xml(file)

    urls.each do |u|
      bf = BsbFeed.new(url: u)
      if bf.valid?
        bsb_feeds << BsbFeed.new(url: u)
      end
    end

    bsb_feeds.each do |bf|
      bf.update_feed
    end
  end

  def create_user_stats
    self.user_stats = UserStats.new(:total_read => 0)
    #user_stats.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    unless @user.user_stats
      @user.create_user_stats
    end
    @bsb_feeds = @user.bsb_feeds

    if(current_user != @user)
      respond_to do |format|
        format.html { redirect_to users_path, notice: "Not allowed to view other user's feeds" }
        format.json { head :no_content }
      end
    end
  end

  def import_feeds
    @user = current_user
  end

  def do_feed_import

    if params[:user]
      uploadfile = params[:user][:importfile]
      #f = File.open(Rails.root.join('public','uploads',uploadfile.original_filename))
      current_user.import_feeds(uploadfile)
    end

    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :no_content }
    end
  end

  def remove_all_feeds
    current_user.remove_all_feeds
    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :no_content }
    end
  end

  def feeds
    @user = User.find(params[:id])
    @bsb_feeds = @user.bsb_feeds

    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  def show_current
    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :no_content }
    end
  end

  def refresh
    current_user.refresh_stats

    respond_to do |format|
      format.html {redirect_to current_user}
      format.json { head :no_content }
    end
  end

  def fetch
    current_user.refresh_stats

    respond_to do |format|
      format.html {redirect_to current_user}
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/feeds.html.erb
<h1>Listing Feeds For <%= @user.email %></h1>

<%= link_to 'All', all_bsb_feeds_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Last update</th>
    <th>Url</th>
    <th>Read index</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bsb_feeds.each do |bsb_feed| %>
  <tr>
    <td><%= bsb_feed.title %></td>
    <td><%= bsb_feed.last_update %></td>
    <td><%= bsb_feed.url %></td>
    <td><%= bsb_feed.read_index %></td>
    <td><%= link_to 'Show', bsb_feed %></td>
    <td><%= link_to 'Edit', edit_bsb_feed_path(bsb_feed) %></td>
    <td><%= link_to 'Remove', bsb_feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<td><%= link_to 'Remove All', remove_all_feeds_path, data: { confirm: 'Are you sure?' } %></td>
<%= link_to 'New Bsb feed', new_bsb_feed_path, data: { keybinding: 'a' }  %>
<%= link_to 'Import Feeds', import_feeds_path %>
<%= link_to 'Back', current_user, data: { keybinding: 'b' }  %>

app/views/users/import_feeds.html.erb
<h1>Import Feeds</h1>

<%= form_for @user, url: do_feed_import_path do |f| %>
  <%= f.file_field :importfile %>
  <%= f.submit "Submit" %>
<% end  %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Users</h1>
<li>Signed in as <%= @user.email %></li>

<%= link_to 'logout', destroy_user_session_path %>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <!-- <td><%= link_to 'Edit', edit_bsb_feed_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New user', new_user_session_path, data: { keybinding: 'a' }  %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.email %><h1>

<h2>
<%= link_to "Feeds", user_feeds_path(@user) %>
<%= link_to "Flavors", flavors_path %>
<%= link_to "Fetch New Stories", fetch_user_stories_path %>
</h2>

<li><%= link_to "Log Out", destroy_user_session_path %></li>