config/routes.rb
BottomlessSoupBowl::Application.routes.draw do

  get "users/index"
  get "users/show"

  devise_for :users

  resources :flavors
  resources :bsb_feeds

  match 'bsb_feeds/:id/refresh' => 'bsb_feeds#refresh', :as => :refresh_bsb_feed
  match 'bsb_feeds/:id/next' => 'bsb_feeds#next', :as => :next_feed_story
  match 'bsb_feeds/:id/prev' => 'bsb_feeds#prev', :as => :prev_feed_story
  match 'bsb_feeds/:id/start' => 'bsb_feeds#start', :as => :start_feed_story

  match 'all_bsb_feeds' => 'bsb_feeds#all', :as => :all_bsb_feeds

  match 'all_bsb_feeds/refresh' => 'bsb_feeds#refresh_all', :as => :refresh_all
  match 'all_bsb_feeds/next' => 'bsb_feeds#next_all', :as => :next_all_story
  match 'all_bsb_feeds/prev' => 'bsb_feeds#prev_all', :as => :prev_all_story
  match 'all_bsb_feeds/start' => 'bsb_feeds#start_all', :as => :start_all_story

  match 'users/showfeeds/:id' => 'users#show', :as => :user

  match 'flavors/:id/refresh' => 'flavors#calculate_scores', :as => :calculate_flavor_scores
  match 'flavors/:id/next' => 'flavors#next', :as => :next_flavor_story
  match 'flavors/:id/prev' => 'flavors#prev', :as => :prev_flavor_story
  match 'flavors/:id/start' => 'flavors#start', :as => :start_flavor_story

  match 'flavors/:id/set_algorithm' => 'flavors#set_algorithm', :as => :set_flavor_algorithm

  match 'users' => 'users#index'
  match 'users/fetch' => 'users#fetch', :as => :fetch_user_stories

  match 'users/:id/feeds' => 'users#feeds', :as => :user_feeds

  match 'import_feeds' => 'users#import_feeds', :as => :import_feeds

  match 'do_feed_import' => 'users#do_feed_import', :as => :do_feed_import

  match 'remove_all_feeds' => 'users#remove_all_feeds', :as => :remove_all_feeds

  root :to => 'users', :action => 'show_current'

end

app/models/bsb_feed.rb
class BsbFeed < ActiveRecord::Base
  attr_accessible :last_update, :read_index, :title, :url
  #validates :title, presence: true
  validates_with FeedValidator
  #validates :url, uniqueness: true, presence: true
  # validates_uniqueness_of :url, :scope => [:session_id]

  has_many :stories
  has_and_belongs_to_many :users
  belongs_to :flavor

  def reload_attributes
    @feed = Feedzirra::Feed.fetch_and_parse(url)
    if(@feed && !(@feed.is_a? Fixnum))
      stories.destroy_all
      @feed.entries.each do |entry|
        stories.build(summary: entry.summary, title: entry.title, url: entry.url,
          published: entry.published, content: entry.content, author: entry.author)
      end
      @ordered_stories = stories.order("published DESC")
      self.last_update = @feed.last_modified
      self.read_index = 0
      self.title = @feed.title
    end
  end

  def update_feed
    if !@feed
      reload_attributes
    end
    if(@feed && !(@feed.is_a? Fixnum))
      @feed = Feedzirra::Feed.update(@feed)
    end
    if !@feed
      logger.error("Null feed")
    elsif @feed.is_a? Array
      logger.error("Feed is array for #{url}")
    elsif @feed.is_a? Fixnum
      logger.error("Failed to read feed for #{url}")
    elsif !@feed.new_entries.empty?
      @feed.new_entries.each do |entry|
        stories.build(summary: entry.summary, title: entry.title, url: entry.url, published: entry.published, content: entry.content)
      end
      self.last_update = @feed.last_modified
    end
    @ordered_stories = stories.all.sort_by(&:published).reverse
    self.save
  end

  def current_story
    if(!@ordered_stories || @ordered_stories.empty)
      @ordered_stories = stories.all.sort_by(&:published).reverse
    end
    @ordered_stories[read_index]
  end

  def next_article
    unless stories[read_index+1].nil?
      self.read_index+=1
      self.save
    end
  end

  def prev_article
    unless stories[read_index-1].nil? || read_index == 0
      self.read_index-=1
      self.save
    end
  end

  def set_user(usar)
    self.user = usar
    self.save
  end
end

app/controllers/bsb_feeds_controller.rb
class BsbFeedsController < ApplicationController
  # GET /bsb_feeds
  # GET /bsb_feeds.json
  def index
    @bsb_feeds = BsbFeed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bsb_feeds }
    end
  end

  # GET /bsb_feeds/1
  # GET /bsb_feeds/1.json
  def show
    @bsb_feed = BsbFeed.find(params[:id])
    @story = @bsb_feed.current_story
    @user = current_user
    if @story.nil?
      @bsb_feed.update_feed
      @story = @bsb_feed.current_story
    end

    @stitle = @story.title
    @surl = @story.url
    @spublished = @story.published
    if @story.content
      @scontent = @story.content.sanitize.html_safe
    elsif @story.summary
      @scontent = @story.summary.sanitize.html_safe
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bsb_feed }
    end
  end

  # GET /bsb_feeds/new
  # GET /bsb_feeds/new.json
  def new
    @bsb_feed = BsbFeed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bsb_feed }
    end
  end

  # GET /bsb_feeds/1/edit
  def edit
    @bsb_feed = BsbFeed.find(params[:id])
  end

  # POST /bsb_feeds
  # POST /bsb_feeds.json
  def create
    @bsb_feed = BsbFeed.new(params[:bsb_feed])
    #if BsbFeed exists with same url, use it instead
    @bsb_feed.users << current_user

    if @bsb_feed.valid?
      @bsb_feed.update_feed
    end

    respond_to do |format|
      if @bsb_feed.save
        format.html { redirect_to @bsb_feed, notice: 'Bsb feed was successfully created.' }
        format.json { render json: @bsb_feed, status: :created, location: @bsb_feed }
      else
        format.html { render action: "new" }
        format.json { render json: @bsb_feed.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /bsb_feeds/1
  # PUT /bsb_feeds/1.json
  def update
    @bsb_feed = BsbFeed.find(params[:id])

    respond_to do |format|
      if @bsb_feed.update_attributes(params[:bsb_feed])
        format.html { redirect_to @bsb_feed, notice: 'Bsb feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bsb_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bsb_feeds/1
  # DELETE /bsb_feeds/1.json
  def destroy
    @bsb_feed = BsbFeed.find(params[:id])
    @bsb_feed.destroy

    respond_to do |format|
      format.html { redirect_to bsb_feeds_url }
      format.json { head :no_content }
    end
  end

  def refresh
    @bsb_feed = BsbFeed.find(params[:id])
    @bsb_feed.update_feed

    respond_to do |format|
      format.html { redirect_to @bsb_feed }
      format.json { head :no_content }
    end
  end

  def refresh_all
    BsbFeed.all.each do |bfeed|
      bfeed.update_feed
    end

    respond_to do |format|
      format.html { redirect_to all_bsb_feeds_path  }
      format.json { head :no_content }
    end
  end

  def next
    @bsb_feed = BsbFeed.find(params[:id])
    @bsb_feed.next_article
    # @bsb_feed.read_index+=1
    # @bsb_feed.save

    respond_to do |format|
      format.html { redirect_to @bsb_feed  }
      format.json { head :no_content }
    end
  end

  def prev
    @bsb_feed = BsbFeed.find(params[:id])
    @bsb_feed.prev_article
    # @bsb_feed.read_index-=1
    # @bsb_feed.save

    respond_to do |format|
      format.html { redirect_to @bsb_feed  }
      format.json { head :no_content }
    end
  end

  def start
    @bsb_feed = BsbFeed.find(params[:id])
    @bsb_feed.read_index = 0
    @bsb_feed.save

    respond_to do |format|
      format.html { redirect_to @bsb_feed  }
      format.json { head :no_content }
    end
  end

  def next_all
    session[:all_index]+=1

    respond_to do |format|
      format.html { redirect_to all_bsb_feeds_path  }
      format.json { head :no_content }
    end
  end

  def prev_all
    session[:all_index] -= 1

    respond_to do |format|
      format.html { redirect_to all_bsb_feeds_path  }
      format.json { head :no_content }
    end
  end

  def start_all
    session[:all_index] = 0
    respond_to do |format|
      format.html { redirect_to all_bsb_feeds_path  }
      format.json { head :no_content }
    end
  end

  def all
    if session[:all_index].nil?
      session[:all_index] = 0
    end

    @story = Story.all.sort_by(&:published).reverse[session[:all_index]]
    # if !@story.bsb_feed.user
    #   @story.bsb_feed.set_user(current_user)
    # end

    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end
end

app/helpers/bsb_feeds_helper.rb
module BsbFeedsHelper
end

app/views/bsb_feeds/_form.html.erb
<%= form_for(@bsb_feed) do |f| %>
  <% if @bsb_feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bsb_feed.errors.count, "error") %> prohibited this bsb_feed from being saved:</h2>

      <ul>
      <% @bsb_feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :last_update %><br />
    <%= f.time_select :last_update %>
  </div> -->
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
 <!--  <div class="field">
    <%= f.label :read_index %><br />
    <%= f.number_field :read_index %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bsb_feeds/all.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Prev', prev_all_story_path, data: { keybinding: 'k' } %>
<%= link_to 'Next', next_all_story_path, data: { keybinding: 'j' } %>

<%= render @story %>


<%= link_to 'Start',start_all_story_path,  data: { keybinding: 'q' } %>
<%= link_to 'Prev (k)', prev_all_story_path %>
<%= link_to 'Next (j)', next_all_story_path %>
<p></p>
<%= link_to 'Back', bsb_feeds_path, data: { keybinding: 'b' } %> |
<%= link_to 'Refresh', refresh_all_path, data: { keybinding: 'r' } %>
<%= link_to '', new_bsb_feed_path, data: { keybinding: 'a' } %>

<p>
  <b>Read index:</b>
  <%= session[:all_index]%>
</p>

app/views/bsb_feeds/edit.html.erb
<h1>Editing bsb_feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @bsb_feed %> |
<%= link_to 'Back', bsb_feeds_path %>

app/views/bsb_feeds/index.html.erb
<h1>Listing Feeds</h1>

<%= link_to 'All', all_bsb_feeds_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Last update</th>
    <th>Url</th>
    <th>Read index</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bsb_feeds.each do |bsb_feed| %>
  <tr>
    <td><%= bsb_feed.title %></td>
    <td><%= bsb_feed.last_update %></td>
    <td><%= bsb_feed.url %></td>
    <td><%= bsb_feed.read_index %></td>
    <td><%= link_to 'Show', bsb_feed %></td>
    <td><%= link_to 'Edit', edit_bsb_feed_path(bsb_feed) %></td>
    <td><%= link_to 'Destroy', bsb_feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bsb feed', new_bsb_feed_path, data: { keybinding: 'a' }  %>

app/views/bsb_feeds/new.html.erb
<h1>New bsb_feed</h1>

<%= render 'form' %>

<%= link_to 'Back', bsb_feeds_path %>

app/views/bsb_feeds/nostories.html.erb
<h1>No stories to display!</h1>

app/views/bsb_feeds/show.html.erb
<%= javascript_include_tag "shortcut.js " %>

<p id="notice"><%= notice %></p>


<%= link_to 'Prev', prev_feed_story_path(@bsb_feed), data: { keybinding: 'k' } %>
<%= link_to 'Next', next_feed_story_path(@bsb_feed), data: { keybinding: 'j' } %>

<%= render @story %>


<%= link_to 'Start',start_feed_story_path(@bsb_feed), data: { keybinding: 'q' } %>
<%= link_to 'Prev (k)', prev_feed_story_path(@bsb_feed) %>
<%= link_to 'Next (j)', next_feed_story_path(@bsb_feed) %>
<p></p>
<%= link_to 'Back', user_feeds_path(@user), data: { keybinding: 'b' } %> |
<%= link_to 'Refresh', refresh_bsb_feed_path(@bsb_feed), data: { keybinding: 'r' } %>
<%= link_to '', new_bsb_feed_path, data: { keybinding: 'a' } %>

<p>
  <b><%= link_to @bsb_feed.title, @bsb_feed.url %></b>
</p>

<p>
  <b>Last update:</b>
  <%= @bsb_feed.last_update %>
</p>

<p>
  <b>Read index:</b>
  <%= @bsb_feed.read_index %>
</p>